### PR TITLE
Enhance Ollama API integration with improved error handling and streaming

### PR DESCRIPTION
**Pull request by polydeuxes**
* **What kind of change does this PR introduce?** 
This PR enhances the Ollama API integration with better error handling and fixes issues with streaming responses.

* **What is the current behavior?** 
The current implementation struggles with parsing streamed responses, leading to frequent JSON parsing errors. It also lacks robust error handling and debugging capabilities.

* **What is the new behavior?** 
The updated implementation:
- Correctly handles chunked responses in the stream, resolving JSON parsing issues
- Improves error handling and adds detailed logging for easier troubleshooting
- Enhances the embedding functionality to use 'prompt' instead of 'input' to align with Ollama's API
- Adds debug options for more visibility into the API interactions

* **Other information**:
This PR focuses on improving the reliability and debuggability of the Ollama API integration. The main challenge was getting the streaming functionality to work correctly, which required careful handling of chunked responses. These changes should make the integration more robust and easier to maintain.

### CODE REVIEW

**Comment by polydeuxes** [comment]
I just realized there's now api.js and api.ts, this may need some work integrating upstream properly

**Comment by dosco** [comment]
all files must have a .ts extension

**Comment by polydeuxes** [comment]
i've been trying to build upstream to test my changes and it's been a learning experience as im not much of a frontend dev. I opened PR 54 to fix some of the spellcheck errors i've been getting. I can get the spellcheck to work if i do npm ci but then i get failure because it doesn't find the tests and fails for 0 tests being done.

**Comment by polydeuxes** [comment]
pushed my changes to the PR branch so they can be reviewed. i need assistance in verifying it builds and correctiveness, i've only been able to do minor things with ollama so far so some functionality might not be needed or be corrected to fit into the ax framework

**Pull request merged**
